name: CI-macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app
    
    - name: Build and test
      run: xcodebuild clean build test -project Gymondo.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
